version: '3'
services:
  blivechat:
    image: xfgryujk/blivechat:latest
    build: ./blivechat/
    ports:
      - "51060:12450"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped
  emotext:
    build: ./emotext/
    ports:
      - "51061:9003"
    restart: unless-stopped
  chatgpt_chatbot:
    build: ./chatgpt_chatbot/
    ports:
      - "51052:50052"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      ## ChatGPTChatbot <--> HTTP Proxy <--> Chat API
      ##
      ## HTTP 代理的地址：
      ## host.docker.internal 是 docker desktop 默认带有的访问宿主机的域名，
      ## 但不一定有效，例如我的 docker vm 访问宿主机的 ip 需要用 192.168.5.2
      #- HTTP_PROXY=http://host.docker.internal:1080
      #- HTTPS_PROXY=http://host.docker.internal:1080
      #
      ## API_URL 是类 ChatGPT 接口的地址，默认是 openai 官方接口。
      ## 可以替换成任何其他兼容的、或代理的接口。
      - API_URL=https://api.openai.com/v1/chat/completions
    restart: unless-stopped
  musharing_chatbot:
    build: ./musharing_chatbot/
    ports:
      - "51051:50051"
    restart: unless-stopped
  live2ddriver:
    build: ./live2ddriver/
    ports:
      - "51071:9001"
      - "51072:9002"
      - "51074:9004"
    environment:
      - EMOTEXT_SERVER=http://emotext:9003
    depends_on:
      - emotext
    restart: unless-stopped
  live2dview:
    build: ./live2dview/
    ports:
      - "51070:80"
    restart: unless-stopped
  externalsayer:
    build: ./externalsayer/
    ports:
      - "51065:50010"
    volumes:
      - ./configs/externalsayer:/app/config
    restart: unless-stopped
  audioview:
    build: ./audioview/
    ports:
      - "51082:80"
    restart: unless-stopped
  muvtuberdriver:
    build: ./muvtuberdriver/
    ports:
      - "51080:51080"
      - "51081:51081"
    volumes:
      - ./configs/muvtuberdriver:/app/config
    depends_on:
      - blivechat
      - live2ddriver
      - musharing_chatbot
      - chatgpt_chatbot
      - externalsayer
    restart: unless-stopped

